---
options:
  sgi:
    description: Name of the network interface to use for sgi
    type: string
  sgi-ipv4-address:
    description: "IPv4 address and netmask (ex: 127.0.0.1/32) of the sgi
                  interface (if not specified, DHCP will be used)"
    type: string
  sgi-ipv4-gateway:
    description: IPv4 gateway address for the sgi interface
    type: string
  sgi-ipv6-address:
    description: "IPv6 address and netmask (ex: ::1/128) of the sgi interface"
    type: string
  sgi-ipv6-gateway:
    description: IPv6 gateway address for the sgi interface
    type: string
  s1:
    description: Name of the network interface to use for s1
    type: string
  s1-ipv4-address:
    description: "IPv4 address and netmask (ex: 127.0.0.1/32) of the s1
                  interface (if not specified, DHCP will be used)"
    type: string
  s1-ipv6-address:
    description: "IPv6 address and netmask (ex: ::1/128) of the s1 interface"
    type: string
  skip-networking:
    description: If true, the installer will skip configuration of networking
    type: boolean
    default: false
  dns:
    description: JSON list of DNS servers to configure
    type: string
    default: '["8.8.8.8", "208.67.222.222"]'
  orc8r-domain:
    description: Orc8r domain.
    type: string
    default: false
  root-ca-path:
    description: rootca.pem path to file.
    type: string
    default: false
