name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  lint-report:
    name: Lint report
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env

      - name: Install tox
        run: pip install tox==$TOX_VERSION

      - name: Run tests using tox
        run: tox -e lint

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.envs

      - name: Install tox
        run: pip install tox==$TOX_VERSION

      - name: Run tests using tox
        run: tox -e static

  unit-tests-with-coverage:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env

      - name: Install tox
        run: pip install tox==$TOX_VERSION

      - name: Run tests using tox
        run: tox -e unit

  charmhub-upload:
    name: Charmhub upload
    runs-on: ubuntu-20.04
    needs:
      - unit-tests-with-coverage
    if: github.ref_name == '1.6'
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env

      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.2.2
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: 1.6/edge
          charmcraft-channel: ${{ env.CHARMCRAFT_VERSION }}
