name: CI

on:
  push:

jobs:
  lint-report:
    name: Lint report
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Install tox
        run: pip install tox==$TOX_VERSION
      - name: Run tests using tox
        run: tox -e lint

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.envs
      - name: Install tox
        run: pip install tox==$TOX_VERSION
      - name: Run tests using tox
        run: tox -e static

  unit-tests-with-coverage:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Install tox
        run: pip install tox==$TOX_VERSION
      - name: Run tests using tox
        run: tox -e unit

  integration-test:
    name: Integration tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Install tox
        run: pip install tox==$TOX_VERSION
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@1.1.0
        with:
          provider: microk8s
          juju-channel: $JUJU_CHANNEL
      - name: Run integration tests
        run: tox -e integration
