name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Promotion process
        options:
          - latest/edge -> latest/beta
          - latest/beta -> latest/candidate

jobs:
  promote:
    name: Promote Charm
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Set target channel
        env:
          PROMOTION: ${{ github.event.inputs.promotion }}
        run: |
          if [ "${PROMOTION}" == "latest/edge -> latest/beta" ]; then
            echo "promote-from=latest/edge" >> ${GITHUB_ENV}
            echo "promote-to=latest/beta" >> ${GITHUB_ENV}
          elif [ "${PROMOTION}" == "latest/beta -> latest/candidate" ]; then
            echo "promote-from=latest/beta" >> ${GITHUB_ENV}
            echo "promote-to=latest/candidate" >> ${GITHUB_ENV}
          fi
      - name: Promote Charm
        uses: canonical/charming-actions/release-charm@2.2.5
        with:
          credentials: ${{ secrets.CHARMCRAFT_AUTH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          destination-channel: ${{ env.promote-to }}
          origin-channel: ${{ env.promote-from }}
          charmcraft-channel: ${{ env.CHARMCRAFT_VERSION }}
