name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Promotion process
        options:
          - 1.6/edge -> 1.6/beta
          - 1.6/beta -> 1.6/candidate
          - 1.6/candidate -> 1.6/stable
          - 1.6/stable -> latest/stable

jobs:
  promote:
    if: github.ref_name == '1.6'
    name: Promote Charm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Set target channel
        env:
          PROMOTION: ${{ github.event.inputs.promotion }}
        run: |
          if [ "${PROMOTION}" == "1.6/edge -> 1.6/beta" ]; then
            echo "promote-from=1.6/edge" >> ${GITHUB_ENV}
            echo "promote-to=1.6/beta" >> ${GITHUB_ENV}
          elif [ "${PROMOTION}" == "1.6/beta -> 1.6/candidate" ]; then
            echo "promote-from=1.6/beta" >> ${GITHUB_ENV}
            echo "promote-to=1.6/candidate" >> ${GITHUB_ENV}
          elif [ "${PROMOTION}" == "1.6/candidate -> 1.6/stable" ]; then
            echo "promote-from=1.6/candidate" >> ${GITHUB_ENV}
            echo "promote-to=1.6/stable" >> ${GITHUB_ENV}
          elif [ "${PROMOTION}" == "1.6/stable -> latest/stable" ]; then
            echo "promote-from=1.6/stable" >> ${GITHUB_ENV}
            echo "promote-to=latest/stable" >> ${GITHUB_ENV}
          fi
      - name: Promote Charm
        uses: canonical/charming-actions/release-charm@2.2.2
        with:
          credentials: ${{ secrets.CHARMCRAFT_AUTH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          destination-channel: ${{ env.promote-to }}
          origin-channel: ${{ env.promote-from }}
          charmcraft-channel: ${{ env.CHARMCRAFT_VERSION }}
